version: 2.1

orbs:
  python: circleci/python@1.2
  heroku: circleci/heroku@0.0.10
  browser-tools: circleci/browser-tools@1.1.3

workflows:
  flask-app-deploy-and-test:
      jobs:
        - heroku/deploy-via-git:
            filters:
              branches:
                only: master
        - test:
            requires:
              - heroku/deploy-via-git
jobs:
  test:
      docker:
      - image: cimg/python:3.9-browsers
      steps:
        - checkout
        - python/install-packages:
            pkg-manager: pip
        - browser-tools/install-chrome
        - browser-tools/install-chromedriver
        - run:
            name: Check chrome install
            command: |
              google-chrome --version
              chromedriver --version
        - run:
            name: Run behave tests
            command: |
              cd test/features
              behave -D url="https://${HEROKU_APP_NAME}.herokuapp.com/"

