version: 2.1

orbs:
  python: circleci/python@1.2
  heroku: circleci/heroku@0.0.10

workflows:
  flask-app-deploy-and-test:
      jobs:
        - heroku/deploy-via-git:
            filters:
              branches:
                only: master
        - test:
            requires:
              - heroku/deploy-via-git
jobs:
  test:
      docker:
      - image: cimg/python:3.8
      steps:
        - checkout
        - python/install-packages:
            pkg-manager: pip
        - run:
            name: Install chromedriver
            command: |
              wget https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
              unzip chromedriver_linux64.zip
              sudo mv chromedriver /usr/bin/chromedriver
              sudo chown root:root /usr/bin/chromedriver
              sudo chmod +x /usr/bin/chromedriver
        - run:
            name: Run behave tests
            command: |
              cd test/features
              behave -D url=https://flask-circleci-epo.herokuapp.com/

