version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  sample:
      jobs:
        - deploy
        - test


jobs:
  deploy:
    machine:
      enabled: true
    environment:
      HEROKU_APP: "flask-circleci-epo"
    steps:
      - checkout
      - run:
          name: Setup Heroku
          command: |
            git push heroku master

  test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Update apt
          command: apt update && apt-upgrade
      - run:
          name: Install chromedriver
          command: apt install chromium-chromedriver
      - run:
          name: Run behave tests
          command: cd test/features && behave
