version: 2.1

orbs:
  python: circleci/python@1.2
  heroku: circleci/heroku@0.0.10
  browser-tools: circleci/browser-tools@1.1.3

workflows:
  flask-app-deploy-and-test:
      jobs:
        - Run unit tests
        - heroku/deploy-via-git:
            filters:
              branches:
                only: master
        - UI post-deploy test:
            requires:
              - heroku/deploy-via-git
jobs:
  Run unit tests:
      docker:
      - image: cimg/python:3.9
      steps:
        - checkout
        - python/install-packages:
            pkg-manager: pip
        - run:
            name: Run unit tests
            command: |
              python -m unittest discover -s test.unit_test
  UI post-deploy test:
      docker:
      - image: cimg/python:3.9-browsers
      steps:
        - checkout
        - python/install-packages:
            pkg-manager: pip
        - browser-tools/install-chrome
        - browser-tools/install-chromedriver
        - run:
            name: Check chrome install
            command: |
              google-chrome --version
              chromedriver --version
        - run:
            name: Run behave post-deploy tests
            command: |
              cd test/post_deploy_test/features
              behave -D url="https://${HEROKU_APP_NAME}.herokuapp.com/"

